apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fleet-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-fleet
  template:
    metadata:
      labels:
        app: nginx-fleet
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80